### ISSUE TITLE
Missing estimated settlement time and settlement status in transaction object

### ISSUE THREAD

**Issue by guzpr** [xendit/xendit-go#102]
https://developers.xendit.co/api-reference/#transaction-object

Missing settlement time and settlement status on transaction object. This field is useful for reconciliation especially for cards payment

**Comment by rjjatson** [comment]
i also need the settlement information, so im proposing a fix here 
https://github.com/xendit/xendit-go/pull/128

would be happy if you could review the PR @adityarx

**Comment by adityarx** [comment]
Merged and released in v1.0.20 @rjjatson @guzpr. Thanks @rjjatson for your fix 🙏
