### ISSUE TITLE
Invoice Params "CustomerNotificationPreference" is not omittable in JSON. Thus impact no customer notifications being sent

### ISSUE THREAD

**Issue by pupleh4t** [xendit/xendit-go#110]
Hi team, kindly look into your struct omitempty implementation. Concrete struct is not omittable, [refer ](https://www.sohamkamani.com/golang/omitempty/)

There are some fields on Xendit API that expects clean omit from payload when there are no values inside of it. I've fixed on my fork by this [commit](https://github.com/pupleh4t/xendit-go/commit/933b8452a91cc65d237755d405b0615a8a3d9b71) for invoice params

Many thanks

**Comment by adityarx** [comment]
Hello @pupleh4t, sorry for the delayed response. We apologize for this, we're a little bit resource constrained. If you're willing to create a pull request for this change with updated tests, we're happy to review! 🙏
