### ISSUE TITLE
How to add api-version when create QR Code Payments

### ISSUE THREAD

**Issue by AzmiFaiz** [xendit/xendit-go#122]
now I'm developing a system using xendit-go by using a QR Code payment but in the documentation I read it is required to add the api-version parameter header to the QR creation request. How do I add the header parameter api-version to the request I made? Thank You

**Comment by adityarx** [comment]
Hello @AzmiFaiz apologies, we are unable to support this at the moment for our V2 QR codes API in Go. 

If you use the existing Create QR API in our Go library, the `api-version` parameter is optional and will create a V1 QR code listed [here](https://developers.xendit.co/api-reference/qr-codes/#qr-codes-v1). However, do note that the V1 API for QR codes will be deprecated soon, so we would not recommend this.

Therefore, we would recommend directly integrating to the V2 QR API. Alternatively, if you are able to raise a pull request with your desired change and tests included, we're happy to review it.

Apologies for the inconvenience 🙏

**Comment by adityarx** [comment]
Closing this issue as answered
