### ISSUE TITLE
is there any predefined callback events struct?

### ISSUE THREAD

**Issue by rjjatson** [xendit/xendit-go#123]
Hi! 
Im having difficulties finding struct to parse xendit incoming callback events. I understand that its entirely possible to create it by ourself by reading the docs. it would be really nice if i can refer it on the xendit sdk itself.
i could help with the implementation if there isn't any just yet.
thanks !

**Comment by adityarx** [comment]
Hi @rjjatson, I'm afraid we don't have this yet. We'd be happy to review a pull request with tests for the callback struct you'd like to add. Let us know which one you're interested in adding, thank you 🙏

**Comment by adityarx** [comment]
Hello @rjjatson, released this as a new version after merging your PR #124. Please upgrade to `v1.0.17`, thanks!
