### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by julianrichie** [xendit/xendit-go#26]
just started out and having issues with invoice module

<img width="1175" alt="Screen Shot 2020-02-29 at 22 16 48" src="https://user-images.githubusercontent.com/1916616/75610196-858f8a00-5b41-11ea-9ec1-531cb82019e2.png">

resolved it by installing the dependencies manually

**Comment by stanleynguyen** [comment]
Hi @julianrichie, thanks for the question. 
Are you using go mod? These 2 deps are declared in our sum file though
https://github.com/xendit/xendit-go/blob/43c8181837f9bc102322932f019d8683c5441cd6/go.sum#L7-L8
https://github.com/xendit/xendit-go/blob/43c8181837f9bc102322932f019d8683c5441cd6/go.sum#L13-L14

**Comment by julianrichie** [comment]
no i'm not using go mod at all

**Comment by stanleynguyen** [comment]
Ah that's why @julianrichie . U gotta `go get` this module `github.com/go-playground/validator/v10`

**Comment by julianrichie** [comment]
oooo ok, it should be answering my question. thx
