### ISSUE TITLE
Xendit QR Codes or QRIS Implementation ?

### ISSUE THREAD

**Issue by raditzlawliet** [xendit/xendit-go#52]
is there API implementation or helper for Xendit QR Codes or QRIS implementation include the example ?

ref: https://docs.xendit.co/qr-codes/index.html
ref: https://developers.xendit.co/api-reference/#qr-codes

**Comment by stanleynguyen** [comment]
Hi @raditzlawliet, QRCode is not supported for `xendit-go` yet. Rest assured it's in our roadmap :)
