### ISSUE TITLE
Request for xenPlatform APIs

### ISSUE THREAD

**Issue by obedtandadjaja** [xendit/xendit-go#56]
Currently, I have to create my own implementation to support xenPlatform APIs, e.g. create account, update account, create rule, etc. Given that xenPlatform is still in closed beta it makes sense why this Golang library does not support these APIs yet. 

I am creating this ticket to be notified when xenPlatform APIs are supported in this official library.

**Comment by Gogotchuri** [comment]
I Will take up this issue, make my fork and add functionality. If you don't mind I'll make a pull request later.

**Comment by hecharles** [comment]
hi @obedtandadjaja , this issue has been resolve in PR #93

**Comment by RafatRashid** [comment]
@hecharles PR #93 is missing xenplatform fee creations and integration with invoice, cards and other transactions
