### ISSUE TITLE
E-Wallet channel code as an enum

### ISSUE THREAD

**Issue by riskimidiw** [xendit/xendit-go#68]
Hi, I see in this docs that E-Wallet channel code defined as
```
ID_OVO, ID_DANA, ID_LINKAJA, ID_SHOPEEPAY, ID_SAKUKU, PH_PAYMAYA,PH_GCASH, PH_GRABPAY
```

**Code**: https://github.com/xendit/xendit-go/blob/fe95496920b8b4e0b024842c87ab72e453f5d8a0/ewallet.go#L44
**Docs**: https://developers.xendit.co/api-reference/?bash#create-ewallet-charge

Can we make E-Wallet channel code as an enum? So we can easily compare this value using this library

```
type EWalletChannelCodeEnum string

const (
  EWalletChannelCodeOVO EWalletChannelCodeEnum = "ID_OVO"
  ...
)
```

**Comment by adityarx** [comment]
Closing this as stale, but if you'd like to add this to our library we're happy to approve and release it~
