### ISSUE TITLE
Invoice: failed to parse payload callback QRIS

### ISSUE THREAD

**Issue by exneval** [xendit/xendit-go#96]
```
// InvoiceFInvoicePaymentDetaile is data that contained in `Invoice` at PaymentDetail
type InvoicePaymentDetail struct {
    Type  string  `json:"receipt_id,omitempty"`
    Value float64 `json:"source,omitempty"`
 }
```

since v1.0.3
`InvoicePaymentDetail.Value` change to `float64`
Refer to this [commit](https://github.com/xendit/xendit-go/commit/3c21c9819017bf9c3beb4bc4caaae923297a6a66)

but the payload `payment_details.source` still expect a `string`

this will make the callback event failed to request (status code: 400)

**Comment by hecharles** [comment]
hi @exneval ,this issue has been fixed in PR #97
